CREATE TABLE RetwisPosts (
    PKEY INTEGER NOT NULL,
    PostID INTEGER NOT NULL,
    Timestamp INTEGER NOT NULL,
    UserID INTEGER NOT NULL,
    Post VARCHAR(1000) NOT NULL,
    PRIMARY KEY(PKEY, PostID)
);
PARTITION TABLE RetwisPosts ON COLUMN PKEY;
CREATE INDEX RetwisPostsIndex ON RetwisPosts (UserID);

CREATE TABLE RetwisFollowees (
     PKEY INTEGER NOT NULL,
     UserID INTEGER NOT NULL,
     FolloweeID INTEGER NOT NULL,
     PRIMARY KEY(PKEY, UserID, FolloweeID)
);
PARTITION TABLE RetwisFollowees ON COLUMN PKEY;
CREATE INDEX RetwisFolloweesIndex ON RetwisFollowees (UserID);
